<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('calendar', function () {
    $tmp = [
        [
            'name' => 'prestations Jonathan',
            'id' => '0ijel6fr9raodpin50r648346s@group.calendar.google.com'
        ],
        [
            'name' => 'Tournai - 1',
            'id' => 'rm3e6l1ac4ba5edmnv1ddar7j4@group.calendar.google.com'
        ]
    ];

    echo serialize($tmp);
    die();
});

Route::get('opening', function () {
    $tmp = [
        0 => [
            '00:00' => ['status' => 'closed', 'display' => false],
            '00:30' => ['status' => 'closed', 'display' => false],
            '01:00' => ['status' => 'closed', 'display' => false],
            '01:30' => ['status' => 'closed', 'display' => false],
            '02:00' => ['status' => 'closed', 'display' => false],
            '02:30' => ['status' => 'closed', 'display' => false],
            '03:00' => ['status' => 'closed', 'display' => false],
            '03:30' => ['status' => 'closed', 'display' => false],
            '04:00' => ['status' => 'closed', 'display' => false],
            '04:30' => ['status' => 'closed', 'display' => false],
            '05:00' => ['status' => 'closed', 'display' => false],
            '05:30' => ['status' => 'closed', 'display' => false],
            '06:00' => ['status' => 'closed', 'display' => false],
            '06:30' => ['status' => 'closed', 'display' => false],
            '07:00' => ['status' => 'closed', 'display' => false],
            '07:30' => ['status' => 'closed', 'display' => false],
            '08:00' => ['status' => 'closed', 'display' => false],
            '08:30' => ['status' => 'closed', 'display' => false],
            '09:00' => ['status' => 'closed', 'display' => false],
            '09:30' => ['status' => 'closed', 'display' => false],
            '10:00' => ['status' => 'closed', 'display' => false],
            '10:30' => ['status' => 'closed', 'display' => false],
            '11:00' => ['status' => 'closed', 'display' => false],
            '11:30' => ['status' => 'closed', 'display' => false],
            '12:00' => ['status' => 'closed', 'display' => false],
            '12:30' => ['status' => 'closed', 'display' => false],
            '13:00' => ['status' => 'closed', 'display' => false],
            '13:30' => ['status' => 'closed', 'display' => false],
            '14:00' => ['status' => 'closed', 'display' => false],
            '14:30' => ['status' => 'closed', 'display' => false],
            '15:00' => ['status' => 'closed', 'display' => false],
            '15:30' => ['status' => 'closed', 'display' => false],
            '16:00' => ['status' => 'closed', 'display' => false],
            '16:30' => ['status' => 'closed', 'display' => false],
            '17:00' => ['status' => 'closed', 'display' => false],
            '17:30' => ['status' => 'closed', 'display' => false],
            '18:00' => ['status' => 'closed', 'display' => false],
            '18:30' => ['status' => 'closed', 'display' => false],
            '19:00' => ['status' => 'closed', 'display' => false],
            '19:30' => ['status' => 'closed', 'display' => false],
            '20:00' => ['status' => 'closed', 'display' => false],
            '20:30' => ['status' => 'closed', 'display' => false],
            '21:00' => ['status' => 'closed', 'display' => false],
            '21:30' => ['status' => 'closed', 'display' => false],
            '22:00' => ['status' => 'closed', 'display' => false],
            '22:30' => ['status' => 'closed', 'display' => false],
            '23:00' => ['status' => 'closed', 'display' => false],
            '23:30' => ['status' => 'closed', 'display' => false]
        ],
        1 => [
            '00:00' => ['status' => 'closed', 'display' => false],
            '00:30' => ['status' => 'closed', 'display' => false],
            '01:00' => ['status' => 'closed', 'display' => false],
            '01:30' => ['status' => 'closed', 'display' => false],
            '02:00' => ['status' => 'closed', 'display' => false],
            '02:30' => ['status' => 'closed', 'display' => false],
            '03:00' => ['status' => 'closed', 'display' => false],
            '03:30' => ['status' => 'closed', 'display' => false],
            '04:00' => ['status' => 'closed', 'display' => false],
            '04:30' => ['status' => 'closed', 'display' => false],
            '05:00' => ['status' => 'closed', 'display' => false],
            '05:30' => ['status' => 'closed', 'display' => false],
            '06:00' => ['status' => 'closed', 'display' => false],
            '06:30' => ['status' => 'closed', 'display' => false],
            '07:00' => ['status' => 'closed', 'display' => false],
            '07:30' => ['status' => 'closed', 'display' => false],
            '08:00' => ['status' => 'closed', 'display' => false],
            '08:30' => ['status' => 'closed', 'display' => false],
            '09:00' => ['status' => 'opened', 'display' => true],
            '09:30' => ['status' => 'opened', 'display' => true],
            '10:00' => ['status' => 'opened', 'display' => true],
            '10:30' => ['status' => 'opened', 'display' => true],
            '11:00' => ['status' => 'opened', 'display' => true],
            '11:30' => ['status' => 'opened', 'display' => true],
            '12:00' => ['status' => 'closed', 'display' => true],
            '12:30' => ['status' => 'closed', 'display' => true],
            '13:00' => ['status' => 'opened', 'display' => true],
            '13:30' => ['status' => 'opened', 'display' => true],
            '14:00' => ['status' => 'opened', 'display' => true],
            '14:30' => ['status' => 'opened', 'display' => true],
            '15:00' => ['status' => 'opened', 'display' => true],
            '15:30' => ['status' => 'opened', 'display' => true],
            '16:00' => ['status' => 'opened', 'display' => true],
            '16:30' => ['status' => 'opened', 'display' => true],
            '17:00' => ['status' => 'opened', 'display' => true],
            '17:30' => ['status' => 'opened', 'display' => true],
            '18:00' => ['status' => 'closed', 'display' => false],
            '18:30' => ['status' => 'closed', 'display' => false],
            '19:00' => ['status' => 'closed', 'display' => false],
            '19:30' => ['status' => 'closed', 'display' => false],
            '20:00' => ['status' => 'closed', 'display' => false],
            '20:30' => ['status' => 'closed', 'display' => false],
            '21:00' => ['status' => 'closed', 'display' => false],
            '21:30' => ['status' => 'closed', 'display' => false],
            '22:00' => ['status' => 'closed', 'display' => false],
            '22:30' => ['status' => 'closed', 'display' => false],
            '23:00' => ['status' => 'closed', 'display' => false],
            '23:30' => ['status' => 'closed', 'display' => false]
        ],
        2 => [
            '00:00' => ['status' => 'closed', 'display' => false],
            '00:30' => ['status' => 'closed', 'display' => false],
            '01:00' => ['status' => 'closed', 'display' => false],
            '01:30' => ['status' => 'closed', 'display' => false],
            '02:00' => ['status' => 'closed', 'display' => false],
            '02:30' => ['status' => 'closed', 'display' => false],
            '03:00' => ['status' => 'closed', 'display' => false],
            '03:30' => ['status' => 'closed', 'display' => false],
            '04:00' => ['status' => 'closed', 'display' => false],
            '04:30' => ['status' => 'closed', 'display' => false],
            '05:00' => ['status' => 'closed', 'display' => false],
            '05:30' => ['status' => 'closed', 'display' => false],
            '06:00' => ['status' => 'closed', 'display' => false],
            '06:30' => ['status' => 'closed', 'display' => false],
            '07:00' => ['status' => 'closed', 'display' => false],
            '07:30' => ['status' => 'closed', 'display' => false],
            '08:00' => ['status' => 'closed', 'display' => false],
            '08:30' => ['status' => 'closed', 'display' => false],
            '09:00' => ['status' => 'opened', 'display' => true],
            '09:30' => ['status' => 'opened', 'display' => true],
            '10:00' => ['status' => 'opened', 'display' => true],
            '10:30' => ['status' => 'opened', 'display' => true],
            '11:00' => ['status' => 'opened', 'display' => true],
            '11:30' => ['status' => 'opened', 'display' => true],
            '12:00' => ['status' => 'closed', 'display' => true],
            '12:30' => ['status' => 'closed', 'display' => true],
            '13:00' => ['status' => 'opened', 'display' => true],
            '13:30' => ['status' => 'opened', 'display' => true],
            '14:00' => ['status' => 'opened', 'display' => true],
            '14:30' => ['status' => 'opened', 'display' => true],
            '15:00' => ['status' => 'opened', 'display' => true],
            '15:30' => ['status' => 'opened', 'display' => true],
            '16:00' => ['status' => 'opened', 'display' => true],
            '16:30' => ['status' => 'opened', 'display' => true],
            '17:00' => ['status' => 'opened', 'display' => true],
            '17:30' => ['status' => 'opened', 'display' => true],
            '18:00' => ['status' => 'closed', 'display' => false],
            '18:30' => ['status' => 'closed', 'display' => false],
            '19:00' => ['status' => 'closed', 'display' => false],
            '19:30' => ['status' => 'closed', 'display' => false],
            '20:00' => ['status' => 'closed', 'display' => false],
            '20:30' => ['status' => 'closed', 'display' => false],
            '21:00' => ['status' => 'closed', 'display' => false],
            '21:30' => ['status' => 'closed', 'display' => false],
            '22:00' => ['status' => 'closed', 'display' => false],
            '22:30' => ['status' => 'closed', 'display' => false],
            '23:00' => ['status' => 'closed', 'display' => false],
            '23:30' => ['status' => 'closed', 'display' => false]
        ],
        3 => [
            '00:00' => ['status' => 'closed', 'display' => false],
            '00:30' => ['status' => 'closed', 'display' => false],
            '01:00' => ['status' => 'closed', 'display' => false],
            '01:30' => ['status' => 'closed', 'display' => false],
            '02:00' => ['status' => 'closed', 'display' => false],
            '02:30' => ['status' => 'closed', 'display' => false],
            '03:00' => ['status' => 'closed', 'display' => false],
            '03:30' => ['status' => 'closed', 'display' => false],
            '04:00' => ['status' => 'closed', 'display' => false],
            '04:30' => ['status' => 'closed', 'display' => false],
            '05:00' => ['status' => 'closed', 'display' => false],
            '05:30' => ['status' => 'closed', 'display' => false],
            '06:00' => ['status' => 'closed', 'display' => false],
            '06:30' => ['status' => 'closed', 'display' => false],
            '07:00' => ['status' => 'closed', 'display' => false],
            '07:30' => ['status' => 'closed', 'display' => false],
            '08:00' => ['status' => 'closed', 'display' => false],
            '08:30' => ['status' => 'closed', 'display' => false],
            '09:00' => ['status' => 'opened', 'display' => true],
            '09:30' => ['status' => 'opened', 'display' => true],
            '10:00' => ['status' => 'opened', 'display' => true],
            '10:30' => ['status' => 'opened', 'display' => true],
            '11:00' => ['status' => 'opened', 'display' => true],
            '11:30' => ['status' => 'opened', 'display' => true],
            '12:00' => ['status' => 'closed', 'display' => true],
            '12:30' => ['status' => 'closed', 'display' => true],
            '13:00' => ['status' => 'opened', 'display' => true],
            '13:30' => ['status' => 'opened', 'display' => true],
            '14:00' => ['status' => 'opened', 'display' => true],
            '14:30' => ['status' => 'opened', 'display' => true],
            '15:00' => ['status' => 'opened', 'display' => true],
            '15:30' => ['status' => 'opened', 'display' => true],
            '16:00' => ['status' => 'opened', 'display' => true],
            '16:30' => ['status' => 'opened', 'display' => true],
            '17:00' => ['status' => 'opened', 'display' => true],
            '17:30' => ['status' => 'opened', 'display' => true],
            '18:00' => ['status' => 'closed', 'display' => false],
            '18:30' => ['status' => 'closed', 'display' => false],
            '19:00' => ['status' => 'closed', 'display' => false],
            '19:30' => ['status' => 'closed', 'display' => false],
            '20:00' => ['status' => 'closed', 'display' => false],
            '20:30' => ['status' => 'closed', 'display' => false],
            '21:00' => ['status' => 'closed', 'display' => false],
            '21:30' => ['status' => 'closed', 'display' => false],
            '22:00' => ['status' => 'closed', 'display' => false],
            '22:30' => ['status' => 'closed', 'display' => false],
            '23:00' => ['status' => 'closed', 'display' => false],
            '23:30' => ['status' => 'closed', 'display' => false]
        ],
        4 => [
            '00:00' => ['status' => 'closed', 'display' => false],
            '00:30' => ['status' => 'closed', 'display' => false],
            '01:00' => ['status' => 'closed', 'display' => false],
            '01:30' => ['status' => 'closed', 'display' => false],
            '02:00' => ['status' => 'closed', 'display' => false],
            '02:30' => ['status' => 'closed', 'display' => false],
            '03:00' => ['status' => 'closed', 'display' => false],
            '03:30' => ['status' => 'closed', 'display' => false],
            '04:00' => ['status' => 'closed', 'display' => false],
            '04:30' => ['status' => 'closed', 'display' => false],
            '05:00' => ['status' => 'closed', 'display' => false],
            '05:30' => ['status' => 'closed', 'display' => false],
            '06:00' => ['status' => 'closed', 'display' => false],
            '06:30' => ['status' => 'closed', 'display' => false],
            '07:00' => ['status' => 'closed', 'display' => false],
            '07:30' => ['status' => 'closed', 'display' => false],
            '08:00' => ['status' => 'closed', 'display' => false],
            '08:30' => ['status' => 'closed', 'display' => false],
            '09:00' => ['status' => 'opened', 'display' => true],
            '09:30' => ['status' => 'opened', 'display' => true],
            '10:00' => ['status' => 'opened', 'display' => true],
            '10:30' => ['status' => 'opened', 'display' => true],
            '11:00' => ['status' => 'opened', 'display' => true],
            '11:30' => ['status' => 'opened', 'display' => true],
            '12:00' => ['status' => 'closed', 'display' => true],
            '12:30' => ['status' => 'closed', 'display' => true],
            '13:00' => ['status' => 'opened', 'display' => true],
            '13:30' => ['status' => 'opened', 'display' => true],
            '14:00' => ['status' => 'opened', 'display' => true],
            '14:30' => ['status' => 'opened', 'display' => true],
            '15:00' => ['status' => 'opened', 'display' => true],
            '15:30' => ['status' => 'opened', 'display' => true],
            '16:00' => ['status' => 'opened', 'display' => true],
            '16:30' => ['status' => 'opened', 'display' => true],
            '17:00' => ['status' => 'opened', 'display' => true],
            '17:30' => ['status' => 'opened', 'display' => true],
            '18:00' => ['status' => 'closed', 'display' => false],
            '18:30' => ['status' => 'closed', 'display' => false],
            '19:00' => ['status' => 'closed', 'display' => false],
            '19:30' => ['status' => 'closed', 'display' => false],
            '20:00' => ['status' => 'closed', 'display' => false],
            '20:30' => ['status' => 'closed', 'display' => false],
            '21:00' => ['status' => 'closed', 'display' => false],
            '21:30' => ['status' => 'closed', 'display' => false],
            '22:00' => ['status' => 'closed', 'display' => false],
            '22:30' => ['status' => 'closed', 'display' => false],
            '23:00' => ['status' => 'closed', 'display' => false],
            '23:30' => ['status' => 'closed', 'display' => false]
        ],
        5 => [
            '00:00' => ['status' => 'closed', 'display' => false],
            '00:30' => ['status' => 'closed', 'display' => false],
            '01:00' => ['status' => 'closed', 'display' => false],
            '01:30' => ['status' => 'closed', 'display' => false],
            '02:00' => ['status' => 'closed', 'display' => false],
            '02:30' => ['status' => 'closed', 'display' => false],
            '03:00' => ['status' => 'closed', 'display' => false],
            '03:30' => ['status' => 'closed', 'display' => false],
            '04:00' => ['status' => 'closed', 'display' => false],
            '04:30' => ['status' => 'closed', 'display' => false],
            '05:00' => ['status' => 'closed', 'display' => false],
            '05:30' => ['status' => 'closed', 'display' => false],
            '06:00' => ['status' => 'closed', 'display' => false],
            '06:30' => ['status' => 'closed', 'display' => false],
            '07:00' => ['status' => 'closed', 'display' => false],
            '07:30' => ['status' => 'closed', 'display' => false],
            '08:00' => ['status' => 'closed', 'display' => false],
            '08:30' => ['status' => 'closed', 'display' => false],
            '09:00' => ['status' => 'opened', 'display' => true],
            '09:30' => ['status' => 'opened', 'display' => true],
            '10:00' => ['status' => 'opened', 'display' => true],
            '10:30' => ['status' => 'opened', 'display' => true],
            '11:00' => ['status' => 'opened', 'display' => true],
            '11:30' => ['status' => 'opened', 'display' => true],
            '12:00' => ['status' => 'closed', 'display' => true],
            '12:30' => ['status' => 'closed', 'display' => true],
            '13:00' => ['status' => 'opened', 'display' => true],
            '13:30' => ['status' => 'opened', 'display' => true],
            '14:00' => ['status' => 'opened', 'display' => true],
            '14:30' => ['status' => 'opened', 'display' => true],
            '15:00' => ['status' => 'opened', 'display' => true],
            '15:30' => ['status' => 'closed', 'display' => false],
            '16:00' => ['status' => 'closed', 'display' => false],
            '16:30' => ['status' => 'closed', 'display' => false],
            '17:00' => ['status' => 'closed', 'display' => false],
            '17:30' => ['status' => 'closed', 'display' => false],
            '18:00' => ['status' => 'closed', 'display' => false],
            '18:30' => ['status' => 'closed', 'display' => false],
            '19:00' => ['status' => 'closed', 'display' => false],
            '19:30' => ['status' => 'closed', 'display' => false],
            '20:00' => ['status' => 'closed', 'display' => false],
            '20:30' => ['status' => 'closed', 'display' => false],
            '21:00' => ['status' => 'closed', 'display' => false],
            '21:30' => ['status' => 'closed', 'display' => false],
            '22:00' => ['status' => 'closed', 'display' => false],
            '22:30' => ['status' => 'closed', 'display' => false],
            '23:00' => ['status' => 'closed', 'display' => false],
            '23:30' => ['status' => 'closed', 'display' => false]
        ],
        6 => [
            '00:00' => ['status' => 'closed', 'display' => false],
            '00:30' => ['status' => 'closed', 'display' => false],
            '01:00' => ['status' => 'closed', 'display' => false],
            '01:30' => ['status' => 'closed', 'display' => false],
            '02:00' => ['status' => 'closed', 'display' => false],
            '02:30' => ['status' => 'closed', 'display' => false],
            '03:00' => ['status' => 'closed', 'display' => false],
            '03:30' => ['status' => 'closed', 'display' => false],
            '04:00' => ['status' => 'closed', 'display' => false],
            '04:30' => ['status' => 'closed', 'display' => false],
            '05:00' => ['status' => 'closed', 'display' => false],
            '05:30' => ['status' => 'closed', 'display' => false],
            '06:00' => ['status' => 'closed', 'display' => false],
            '06:30' => ['status' => 'closed', 'display' => false],
            '07:00' => ['status' => 'closed', 'display' => false],
            '07:30' => ['status' => 'closed', 'display' => false],
            '08:00' => ['status' => 'closed', 'display' => false],
            '08:30' => ['status' => 'closed', 'display' => false],
            '09:00' => ['status' => 'opened', 'display' => true],
            '09:30' => ['status' => 'opened', 'display' => true],
            '10:00' => ['status' => 'opened', 'display' => true],
            '10:30' => ['status' => 'opened', 'display' => true],
            '11:00' => ['status' => 'opened', 'display' => true],
            '11:30' => ['status' => 'opened', 'display' => true],
            '12:00' => ['status' => 'closed', 'display' => false],
            '12:30' => ['status' => 'closed', 'display' => false],
            '13:00' => ['status' => 'closed', 'display' => false],
            '13:30' => ['status' => 'closed', 'display' => false],
            '14:00' => ['status' => 'closed', 'display' => false],
            '14:30' => ['status' => 'closed', 'display' => false],
            '15:00' => ['status' => 'closed', 'display' => false],
            '15:30' => ['status' => 'closed', 'display' => false],
            '16:00' => ['status' => 'closed', 'display' => false],
            '16:30' => ['status' => 'closed', 'display' => false],
            '17:00' => ['status' => 'closed', 'display' => false],
            '17:30' => ['status' => 'closed', 'display' => false],
            '18:00' => ['status' => 'closed', 'display' => false],
            '18:30' => ['status' => 'closed', 'display' => false],
            '19:00' => ['status' => 'closed', 'display' => false],
            '19:30' => ['status' => 'closed', 'display' => false],
            '20:00' => ['status' => 'closed', 'display' => false],
            '20:30' => ['status' => 'closed', 'display' => false],
            '21:00' => ['status' => 'closed', 'display' => false],
            '21:30' => ['status' => 'closed', 'display' => false],
            '22:00' => ['status' => 'closed', 'display' => false],
            '22:30' => ['status' => 'closed', 'display' => false],
            '23:00' => ['status' => 'closed', 'display' => false],
            '23:30' => ['status' => 'closed', 'display' => false]
        ]
    ];

    echo serialize($tmp);
    die();
});