<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Garage;

class GaragesController extends Controller
{
    protected function validateRequest()
    {
        return request()->validate([
            'name' => 'nullable',
            'google_calendar' => 'nullable',
            'opening' => 'nullable',
            'status_id' => 'nullable'
        ]);
    }

    public function show(Garage $garage)
    {
        $garage->opening = unserialize($garage->opening);
        $garage->google_calendar = unserialize($garage->google_calendar);

        return response()->json([
            'success' => true,
            'message' => '',
            'data' => ['garage' => $garage]
        ], 200); 
    }

    public function store()
    {
        $data = $this->validateRequest();

        $openings = [
            0 => [
                '00:00' => ['status' => 'closed', 'display' => false],
                '00:30' => ['status' => 'closed', 'display' => false],
                '01:00' => ['status' => 'closed', 'display' => false],
                '01:30' => ['status' => 'closed', 'display' => false],
                '02:00' => ['status' => 'closed', 'display' => false],
                '02:30' => ['status' => 'closed', 'display' => false],
                '03:00' => ['status' => 'closed', 'display' => false],
                '03:30' => ['status' => 'closed', 'display' => false],
                '04:00' => ['status' => 'closed', 'display' => false],
                '04:30' => ['status' => 'closed', 'display' => false],
                '05:00' => ['status' => 'closed', 'display' => false],
                '05:30' => ['status' => 'closed', 'display' => false],
                '06:00' => ['status' => 'closed', 'display' => false],
                '06:30' => ['status' => 'closed', 'display' => false],
                '07:00' => ['status' => 'closed', 'display' => false],
                '07:30' => ['status' => 'closed', 'display' => false],
                '08:00' => ['status' => 'closed', 'display' => false],
                '08:30' => ['status' => 'closed', 'display' => false],
                '09:00' => ['status' => 'closed', 'display' => false],
                '09:30' => ['status' => 'closed', 'display' => false],
                '10:00' => ['status' => 'closed', 'display' => false],
                '10:30' => ['status' => 'closed', 'display' => false],
                '11:00' => ['status' => 'closed', 'display' => false],
                '11:30' => ['status' => 'closed', 'display' => false],
                '12:00' => ['status' => 'closed', 'display' => false],
                '12:30' => ['status' => 'closed', 'display' => false],
                '13:00' => ['status' => 'closed', 'display' => false],
                '13:30' => ['status' => 'closed', 'display' => false],
                '14:00' => ['status' => 'closed', 'display' => false],
                '14:30' => ['status' => 'closed', 'display' => false],
                '15:00' => ['status' => 'closed', 'display' => false],
                '15:30' => ['status' => 'closed', 'display' => false],
                '16:00' => ['status' => 'closed', 'display' => false],
                '16:30' => ['status' => 'closed', 'display' => false],
                '17:00' => ['status' => 'closed', 'display' => false],
                '17:30' => ['status' => 'closed', 'display' => false],
                '18:00' => ['status' => 'closed', 'display' => false],
                '18:30' => ['status' => 'closed', 'display' => false],
                '19:00' => ['status' => 'closed', 'display' => false],
                '19:30' => ['status' => 'closed', 'display' => false],
                '20:00' => ['status' => 'closed', 'display' => false],
                '20:30' => ['status' => 'closed', 'display' => false],
                '21:00' => ['status' => 'closed', 'display' => false],
                '21:30' => ['status' => 'closed', 'display' => false],
                '22:00' => ['status' => 'closed', 'display' => false],
                '22:30' => ['status' => 'closed', 'display' => false],
                '23:00' => ['status' => 'closed', 'display' => false],
                '23:30' => ['status' => 'closed', 'display' => false]
            ],
            1 => [
                '00:00' => ['status' => 'closed', 'display' => false],
                '00:30' => ['status' => 'closed', 'display' => false],
                '01:00' => ['status' => 'closed', 'display' => false],
                '01:30' => ['status' => 'closed', 'display' => false],
                '02:00' => ['status' => 'closed', 'display' => false],
                '02:30' => ['status' => 'closed', 'display' => false],
                '03:00' => ['status' => 'closed', 'display' => false],
                '03:30' => ['status' => 'closed', 'display' => false],
                '04:00' => ['status' => 'closed', 'display' => false],
                '04:30' => ['status' => 'closed', 'display' => false],
                '05:00' => ['status' => 'closed', 'display' => false],
                '05:30' => ['status' => 'closed', 'display' => false],
                '06:00' => ['status' => 'closed', 'display' => false],
                '06:30' => ['status' => 'closed', 'display' => false],
                '07:00' => ['status' => 'closed', 'display' => false],
                '07:30' => ['status' => 'closed', 'display' => false],
                '08:00' => ['status' => 'closed', 'display' => false],
                '08:30' => ['status' => 'closed', 'display' => false],
                '09:00' => ['status' => 'closed', 'display' => false],
                '09:30' => ['status' => 'closed', 'display' => false],
                '10:00' => ['status' => 'closed', 'display' => false],
                '10:30' => ['status' => 'closed', 'display' => false],
                '11:00' => ['status' => 'closed', 'display' => false],
                '11:30' => ['status' => 'closed', 'display' => false],
                '12:00' => ['status' => 'closed', 'display' => false],
                '12:30' => ['status' => 'closed', 'display' => false],
                '13:00' => ['status' => 'closed', 'display' => false],
                '13:30' => ['status' => 'closed', 'display' => false],
                '14:00' => ['status' => 'closed', 'display' => false],
                '14:30' => ['status' => 'closed', 'display' => false],
                '15:00' => ['status' => 'closed', 'display' => false],
                '15:30' => ['status' => 'closed', 'display' => false],
                '16:00' => ['status' => 'closed', 'display' => false],
                '16:30' => ['status' => 'closed', 'display' => false],
                '17:00' => ['status' => 'closed', 'display' => false],
                '17:30' => ['status' => 'closed', 'display' => false],
                '18:00' => ['status' => 'closed', 'display' => false],
                '18:30' => ['status' => 'closed', 'display' => false],
                '19:00' => ['status' => 'closed', 'display' => false],
                '19:30' => ['status' => 'closed', 'display' => false],
                '20:00' => ['status' => 'closed', 'display' => false],
                '20:30' => ['status' => 'closed', 'display' => false],
                '21:00' => ['status' => 'closed', 'display' => false],
                '21:30' => ['status' => 'closed', 'display' => false],
                '22:00' => ['status' => 'closed', 'display' => false],
                '22:30' => ['status' => 'closed', 'display' => false],
                '23:00' => ['status' => 'closed', 'display' => false],
                '23:30' => ['status' => 'closed', 'display' => false]
            ],
            2 => [
                '00:00' => ['status' => 'closed', 'display' => false],
                '00:30' => ['status' => 'closed', 'display' => false],
                '01:00' => ['status' => 'closed', 'display' => false],
                '01:30' => ['status' => 'closed', 'display' => false],
                '02:00' => ['status' => 'closed', 'display' => false],
                '02:30' => ['status' => 'closed', 'display' => false],
                '03:00' => ['status' => 'closed', 'display' => false],
                '03:30' => ['status' => 'closed', 'display' => false],
                '04:00' => ['status' => 'closed', 'display' => false],
                '04:30' => ['status' => 'closed', 'display' => false],
                '05:00' => ['status' => 'closed', 'display' => false],
                '05:30' => ['status' => 'closed', 'display' => false],
                '06:00' => ['status' => 'closed', 'display' => false],
                '06:30' => ['status' => 'closed', 'display' => false],
                '07:00' => ['status' => 'closed', 'display' => false],
                '07:30' => ['status' => 'closed', 'display' => false],
                '08:00' => ['status' => 'closed', 'display' => false],
                '08:30' => ['status' => 'closed', 'display' => false],
                '09:00' => ['status' => 'closed', 'display' => false],
                '09:30' => ['status' => 'closed', 'display' => false],
                '10:00' => ['status' => 'closed', 'display' => false],
                '10:30' => ['status' => 'closed', 'display' => false],
                '11:00' => ['status' => 'closed', 'display' => false],
                '11:30' => ['status' => 'closed', 'display' => false],
                '12:00' => ['status' => 'closed', 'display' => false],
                '12:30' => ['status' => 'closed', 'display' => false],
                '13:00' => ['status' => 'closed', 'display' => false],
                '13:30' => ['status' => 'closed', 'display' => false],
                '14:00' => ['status' => 'closed', 'display' => false],
                '14:30' => ['status' => 'closed', 'display' => false],
                '15:00' => ['status' => 'closed', 'display' => false],
                '15:30' => ['status' => 'closed', 'display' => false],
                '16:00' => ['status' => 'closed', 'display' => false],
                '16:30' => ['status' => 'closed', 'display' => false],
                '17:00' => ['status' => 'closed', 'display' => false],
                '17:30' => ['status' => 'closed', 'display' => false],
                '18:00' => ['status' => 'closed', 'display' => false],
                '18:30' => ['status' => 'closed', 'display' => false],
                '19:00' => ['status' => 'closed', 'display' => false],
                '19:30' => ['status' => 'closed', 'display' => false],
                '20:00' => ['status' => 'closed', 'display' => false],
                '20:30' => ['status' => 'closed', 'display' => false],
                '21:00' => ['status' => 'closed', 'display' => false],
                '21:30' => ['status' => 'closed', 'display' => false],
                '22:00' => ['status' => 'closed', 'display' => false],
                '22:30' => ['status' => 'closed', 'display' => false],
                '23:00' => ['status' => 'closed', 'display' => false],
                '23:30' => ['status' => 'closed', 'display' => false]
            ],
            3 => [
                '00:00' => ['status' => 'closed', 'display' => false],
                '00:30' => ['status' => 'closed', 'display' => false],
                '01:00' => ['status' => 'closed', 'display' => false],
                '01:30' => ['status' => 'closed', 'display' => false],
                '02:00' => ['status' => 'closed', 'display' => false],
                '02:30' => ['status' => 'closed', 'display' => false],
                '03:00' => ['status' => 'closed', 'display' => false],
                '03:30' => ['status' => 'closed', 'display' => false],
                '04:00' => ['status' => 'closed', 'display' => false],
                '04:30' => ['status' => 'closed', 'display' => false],
                '05:00' => ['status' => 'closed', 'display' => false],
                '05:30' => ['status' => 'closed', 'display' => false],
                '06:00' => ['status' => 'closed', 'display' => false],
                '06:30' => ['status' => 'closed', 'display' => false],
                '07:00' => ['status' => 'closed', 'display' => false],
                '07:30' => ['status' => 'closed', 'display' => false],
                '08:00' => ['status' => 'closed', 'display' => false],
                '08:30' => ['status' => 'closed', 'display' => false],
                '09:00' => ['status' => 'closed', 'display' => false],
                '09:30' => ['status' => 'closed', 'display' => false],
                '10:00' => ['status' => 'closed', 'display' => false],
                '10:30' => ['status' => 'closed', 'display' => false],
                '11:00' => ['status' => 'closed', 'display' => false],
                '11:30' => ['status' => 'closed', 'display' => false],
                '12:00' => ['status' => 'closed', 'display' => false],
                '12:30' => ['status' => 'closed', 'display' => false],
                '13:00' => ['status' => 'closed', 'display' => false],
                '13:30' => ['status' => 'closed', 'display' => false],
                '14:00' => ['status' => 'closed', 'display' => false],
                '14:30' => ['status' => 'closed', 'display' => false],
                '15:00' => ['status' => 'closed', 'display' => false],
                '15:30' => ['status' => 'closed', 'display' => false],
                '16:00' => ['status' => 'closed', 'display' => false],
                '16:30' => ['status' => 'closed', 'display' => false],
                '17:00' => ['status' => 'closed', 'display' => false],
                '17:30' => ['status' => 'closed', 'display' => false],
                '18:00' => ['status' => 'closed', 'display' => false],
                '18:30' => ['status' => 'closed', 'display' => false],
                '19:00' => ['status' => 'closed', 'display' => false],
                '19:30' => ['status' => 'closed', 'display' => false],
                '20:00' => ['status' => 'closed', 'display' => false],
                '20:30' => ['status' => 'closed', 'display' => false],
                '21:00' => ['status' => 'closed', 'display' => false],
                '21:30' => ['status' => 'closed', 'display' => false],
                '22:00' => ['status' => 'closed', 'display' => false],
                '22:30' => ['status' => 'closed', 'display' => false],
                '23:00' => ['status' => 'closed', 'display' => false],
                '23:30' => ['status' => 'closed', 'display' => false]
            ],
            4 => [
                '00:00' => ['status' => 'closed', 'display' => false],
                '00:30' => ['status' => 'closed', 'display' => false],
                '01:00' => ['status' => 'closed', 'display' => false],
                '01:30' => ['status' => 'closed', 'display' => false],
                '02:00' => ['status' => 'closed', 'display' => false],
                '02:30' => ['status' => 'closed', 'display' => false],
                '03:00' => ['status' => 'closed', 'display' => false],
                '03:30' => ['status' => 'closed', 'display' => false],
                '04:00' => ['status' => 'closed', 'display' => false],
                '04:30' => ['status' => 'closed', 'display' => false],
                '05:00' => ['status' => 'closed', 'display' => false],
                '05:30' => ['status' => 'closed', 'display' => false],
                '06:00' => ['status' => 'closed', 'display' => false],
                '06:30' => ['status' => 'closed', 'display' => false],
                '07:00' => ['status' => 'closed', 'display' => false],
                '07:30' => ['status' => 'closed', 'display' => false],
                '08:00' => ['status' => 'closed', 'display' => false],
                '08:30' => ['status' => 'closed', 'display' => false],
                '09:00' => ['status' => 'closed', 'display' => false],
                '09:30' => ['status' => 'closed', 'display' => false],
                '10:00' => ['status' => 'closed', 'display' => false],
                '10:30' => ['status' => 'closed', 'display' => false],
                '11:00' => ['status' => 'closed', 'display' => false],
                '11:30' => ['status' => 'closed', 'display' => false],
                '12:00' => ['status' => 'closed', 'display' => false],
                '12:30' => ['status' => 'closed', 'display' => false],
                '13:00' => ['status' => 'closed', 'display' => false],
                '13:30' => ['status' => 'closed', 'display' => false],
                '14:00' => ['status' => 'closed', 'display' => false],
                '14:30' => ['status' => 'closed', 'display' => false],
                '15:00' => ['status' => 'closed', 'display' => false],
                '15:30' => ['status' => 'closed', 'display' => false],
                '16:00' => ['status' => 'closed', 'display' => false],
                '16:30' => ['status' => 'closed', 'display' => false],
                '17:00' => ['status' => 'closed', 'display' => false],
                '17:30' => ['status' => 'closed', 'display' => false],
                '18:00' => ['status' => 'closed', 'display' => false],
                '18:30' => ['status' => 'closed', 'display' => false],
                '19:00' => ['status' => 'closed', 'display' => false],
                '19:30' => ['status' => 'closed', 'display' => false],
                '20:00' => ['status' => 'closed', 'display' => false],
                '20:30' => ['status' => 'closed', 'display' => false],
                '21:00' => ['status' => 'closed', 'display' => false],
                '21:30' => ['status' => 'closed', 'display' => false],
                '22:00' => ['status' => 'closed', 'display' => false],
                '22:30' => ['status' => 'closed', 'display' => false],
                '23:00' => ['status' => 'closed', 'display' => false],
                '23:30' => ['status' => 'closed', 'display' => false]
            ],
            5 => [
                '00:00' => ['status' => 'closed', 'display' => false],
                '00:30' => ['status' => 'closed', 'display' => false],
                '01:00' => ['status' => 'closed', 'display' => false],
                '01:30' => ['status' => 'closed', 'display' => false],
                '02:00' => ['status' => 'closed', 'display' => false],
                '02:30' => ['status' => 'closed', 'display' => false],
                '03:00' => ['status' => 'closed', 'display' => false],
                '03:30' => ['status' => 'closed', 'display' => false],
                '04:00' => ['status' => 'closed', 'display' => false],
                '04:30' => ['status' => 'closed', 'display' => false],
                '05:00' => ['status' => 'closed', 'display' => false],
                '05:30' => ['status' => 'closed', 'display' => false],
                '06:00' => ['status' => 'closed', 'display' => false],
                '06:30' => ['status' => 'closed', 'display' => false],
                '07:00' => ['status' => 'closed', 'display' => false],
                '07:30' => ['status' => 'closed', 'display' => false],
                '08:00' => ['status' => 'closed', 'display' => false],
                '08:30' => ['status' => 'closed', 'display' => false],
                '09:00' => ['status' => 'closed', 'display' => false],
                '09:30' => ['status' => 'closed', 'display' => false],
                '10:00' => ['status' => 'closed', 'display' => false],
                '10:30' => ['status' => 'closed', 'display' => false],
                '11:00' => ['status' => 'closed', 'display' => false],
                '11:30' => ['status' => 'closed', 'display' => false],
                '12:00' => ['status' => 'closed', 'display' => false],
                '12:30' => ['status' => 'closed', 'display' => false],
                '13:00' => ['status' => 'closed', 'display' => false],
                '13:30' => ['status' => 'closed', 'display' => false],
                '14:00' => ['status' => 'closed', 'display' => false],
                '14:30' => ['status' => 'closed', 'display' => false],
                '15:00' => ['status' => 'closed', 'display' => false],
                '15:30' => ['status' => 'closed', 'display' => false],
                '16:00' => ['status' => 'closed', 'display' => false],
                '16:30' => ['status' => 'closed', 'display' => false],
                '17:00' => ['status' => 'closed', 'display' => false],
                '17:30' => ['status' => 'closed', 'display' => false],
                '18:00' => ['status' => 'closed', 'display' => false],
                '18:30' => ['status' => 'closed', 'display' => false],
                '19:00' => ['status' => 'closed', 'display' => false],
                '19:30' => ['status' => 'closed', 'display' => false],
                '20:00' => ['status' => 'closed', 'display' => false],
                '20:30' => ['status' => 'closed', 'display' => false],
                '21:00' => ['status' => 'closed', 'display' => false],
                '21:30' => ['status' => 'closed', 'display' => false],
                '22:00' => ['status' => 'closed', 'display' => false],
                '22:30' => ['status' => 'closed', 'display' => false],
                '23:00' => ['status' => 'closed', 'display' => false],
                '23:30' => ['status' => 'closed', 'display' => false]
            ],
            6 => [
                '00:00' => ['status' => 'closed', 'display' => false],
                '00:30' => ['status' => 'closed', 'display' => false],
                '01:00' => ['status' => 'closed', 'display' => false],
                '01:30' => ['status' => 'closed', 'display' => false],
                '02:00' => ['status' => 'closed', 'display' => false],
                '02:30' => ['status' => 'closed', 'display' => false],
                '03:00' => ['status' => 'closed', 'display' => false],
                '03:30' => ['status' => 'closed', 'display' => false],
                '04:00' => ['status' => 'closed', 'display' => false],
                '04:30' => ['status' => 'closed', 'display' => false],
                '05:00' => ['status' => 'closed', 'display' => false],
                '05:30' => ['status' => 'closed', 'display' => false],
                '06:00' => ['status' => 'closed', 'display' => false],
                '06:30' => ['status' => 'closed', 'display' => false],
                '07:00' => ['status' => 'closed', 'display' => false],
                '07:30' => ['status' => 'closed', 'display' => false],
                '08:00' => ['status' => 'closed', 'display' => false],
                '08:30' => ['status' => 'closed', 'display' => false],
                '09:00' => ['status' => 'closed', 'display' => false],
                '09:30' => ['status' => 'closed', 'display' => false],
                '10:00' => ['status' => 'closed', 'display' => false],
                '10:30' => ['status' => 'closed', 'display' => false],
                '11:00' => ['status' => 'closed', 'display' => false],
                '11:30' => ['status' => 'closed', 'display' => false],
                '12:00' => ['status' => 'closed', 'display' => false],
                '12:30' => ['status' => 'closed', 'display' => false],
                '13:00' => ['status' => 'closed', 'display' => false],
                '13:30' => ['status' => 'closed', 'display' => false],
                '14:00' => ['status' => 'closed', 'display' => false],
                '14:30' => ['status' => 'closed', 'display' => false],
                '15:00' => ['status' => 'closed', 'display' => false],
                '15:30' => ['status' => 'closed', 'display' => false],
                '16:00' => ['status' => 'closed', 'display' => false],
                '16:30' => ['status' => 'closed', 'display' => false],
                '17:00' => ['status' => 'closed', 'display' => false],
                '17:30' => ['status' => 'closed', 'display' => false],
                '18:00' => ['status' => 'closed', 'display' => false],
                '18:30' => ['status' => 'closed', 'display' => false],
                '19:00' => ['status' => 'closed', 'display' => false],
                '19:30' => ['status' => 'closed', 'display' => false],
                '20:00' => ['status' => 'closed', 'display' => false],
                '20:30' => ['status' => 'closed', 'display' => false],
                '21:00' => ['status' => 'closed', 'display' => false],
                '21:30' => ['status' => 'closed', 'display' => false],
                '22:00' => ['status' => 'closed', 'display' => false],
                '22:30' => ['status' => 'closed', 'display' => false],
                '23:00' => ['status' => 'closed', 'display' => false],
                '23:30' => ['status' => 'closed', 'display' => false]
            ],
        ];

        $data['opening'] = serialize($openings);
        $garage = Garage::create($data);

        $garage = Garage::where('id', $garage->id)->first();

        return response()->json([
            'success' => true,
            'message' => '',
            'data' => ['garage' => $garage]
        ], 200);
    }

    public function update(Garage $garage)
    {
        $data = $this->validateRequest();

        $data['opening'] = serialize($data['opening']);
        $data['google_calendar'] = serialize($data['google_calendar']);
        $garage->update($data);

        $garage = Garage::where('id', $garage->id)->first();
        $garage->opening = unserialize($garage->opening);
        $garage->google_calendar = unserialize($garage->google_calendar);

        return response()->json([
            'success' => true,
            'message' => '',
            'data' => ['garage' => $garage]
        ], 200); 
    }

    public function destroy(Garage $garage)
    {
        $garage->delete();
  
        return response()->json([
            'success' => true,
            'message' => '',
            'data' => ''
        ], 200);
    }
}
